version: '3.9'

services:
  remotecert-exporter:
    image: hetimop/remotecert-exporter:v1.0
    environment:
      - URLS="debian.org" "hub.docker.com" # Liste des domaines à vérifier
      - METRICS_PORT=9006  # Remplacement du port d'écooute (par défaut 9999)
    ports:
      - "9006:9006" 