version: '3.9'

services:
  remotecert-exporter:
    image: hetimop/remotecert-exporter:v1.0
    container_name: remotecert-exporter
    restart_policy:
      condition: any
    environment:
      - METRICS_PORT=9007  # Remplacement du port d'écooute (par défaut 9999)
    ports:
      - "9007:9007" 
    deploy:
      placement:
        constraints:
          - node.role == manager