version: '3.9'

services:
  remotecert-exporter:
    image: hetimop/remotecert-exporter:v1.0
    container_name: remotecert-exporter
    environment:
      - URLS="youtube.com:443" "twitter.com:443" # Liste des domaines à vérifier
      - METRICS_PORT=9007  # Remplacement du port d'écooute (par défaut 9999)
    ports:
      - "9007:9007" 