#!/bin/bash

# disable exit on error
set +e

# set the MIME type of the output
mime="text/plain"

# change to the script directory
cd /app/

# loop over all scripts in the directory
for script in metrics.sh
do
  # execute the script and capture the output
  output=$(./$script)

  # get the size of the output
  size=$(echo -n "$output" | wc -c)

  # output the HTTP response header and the script output
  printf 'HTTP/1.1 200 OK\r\nDate: %s\r\nContent-Length: %s\r\nContent-Type: %s\r\nConnection: close\r\n\r\n%s' "$(date)" "$size" "$mime" "$output"
  sleep 1

done

exit 0
